"""Small dependency-free GitHub REST provider."""
from __future__ import annotations

import asyncio
import base64
import json
import urllib.error
import urllib.parse
import urllib.request

from ..domain.errors import GitHubError
from ..domain.types import FileArtifact, MergeResult, PlannedTask
from .base import GitHubProvider


class GitHubRestProvider(GitHubProvider):
    """Publish task artifacts through the GitHub Contents and Pull Requests APIs."""

    def __init__(
        self,
        token: str,
        owner: str,
        repository: str,
        base_url: str = "https://api.github.com",
        timeout: int = 30,
    ) -> None:
        if not token or not owner or not repository:
            raise GitHubError("GitHub token, owner, and repository are required")
        self.token = token
        self.owner = owner
        self.repository = repository
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    async def publish_task(
        self,
        run_id: str,
        task: PlannedTask,
        artifacts: list[FileArtifact],
        base_branch: str,
        create_pull_request: bool = True,
        merge_pull_request: bool = False,
    ) -> MergeResult:
        try:
            branch = f"rmao/{run_id}/{task.branch_slug}"
            await asyncio.to_thread(self._create_branch, branch, base_branch)
            for artifact in artifacts:
                await asyncio.to_thread(self._upsert_file, branch, artifact)
            pr_url = None
            pr_number: int | None = None
            if create_pull_request:
                pr_number, pr_url = await asyncio.to_thread(
                    self._create_pull_request,
                    branch,
                    base_branch,
                    task,
                )
            if merge_pull_request and pr_number is not None:
                await asyncio.to_thread(self._merge_pull_request, pr_number)
            return MergeResult(
                task_id=task.task_id,
                success=True,
                pr_url=pr_url,
                branch_name=branch,
            )
        except GitHubError:
            raise
        except Exception as error:
            raise GitHubError(f"GitHub publish failed for '{task.task_id}': {error}") from error

    def _create_branch(self, branch: str, base_branch: str) -> None:
        ref = self._request(
            "GET",
            f"/repos/{self.owner}/{self.repository}/git/ref/heads/{urllib.parse.quote(base_branch, safe='')}",
        )
        sha = ref.get("object", {}).get("sha")
        if not sha:
            raise GitHubError(f"Could not resolve base branch '{base_branch}'")
        self._request(
            "POST",
            f"/repos/{self.owner}/{self.repository}/git/refs",
            {"ref": f"refs/heads/{branch}", "sha": sha},
        )

    def _upsert_file(self, branch: str, artifact: FileArtifact) -> None:
        path = urllib.parse.quote(artifact.path, safe="/")
        endpoint = f"/repos/{self.owner}/{self.repository}/contents/{path}"
        existing_sha = None
        try:
            existing_sha = self._request(
                "GET",
                f"{endpoint}?ref={urllib.parse.quote(branch, safe='')}",
            ).get("sha")
        except GitHubError as error:
            if "HTTP 404" not in str(error):
                raise
        payload = {
            "message": f"RMAO: update {artifact.path}",
            "content": base64.b64encode(artifact.content.encode("utf-8")).decode("ascii"),
            "branch": branch,
        }
        if existing_sha:
            payload["sha"] = existing_sha
        self._request("PUT", endpoint, payload)

    def _create_pull_request(
        self,
        branch: str,
        base_branch: str,
        task: PlannedTask,
    ) -> tuple[int, str]:
        response = self._request(
            "POST",
            f"/repos/{self.owner}/{self.repository}/pulls",
            {
                "title": f"RMAO: {task.name}",
                "head": branch,
                "base": base_branch,
                "body": (
                    f"Automated RMAO task `{task.task_id}`.\n\n"
                    "Generated by the configured orchestrator workflow."
                ),
            },
        )
        number = response.get("number")
        url = response.get("html_url")
        if not isinstance(number, int) or not isinstance(url, str):
            raise GitHubError("GitHub returned an invalid pull request response")
        return number, url

    def _merge_pull_request(self, number: int) -> None:
        self._request(
            "PUT",
            f"/repos/{self.owner}/{self.repository}/pulls/{number}/merge",
            {"merge_method": "squash"},
        )

    def _request(self, method: str, path: str, payload: dict | None = None) -> dict:
        url = f"{self.base_url}{path}"
        body = json.dumps(payload).encode("utf-8") if payload is not None else None
        request = urllib.request.Request(url, data=body, method=method)
        request.add_header("Accept", "application/vnd.github+json")
        request.add_header("Authorization", "Bearer " + self.token)
        request.add_header("X-GitHub-Api-Version", "2022-11-28")
        if body is not None:
            request.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                raw = response.read().decode("utf-8")
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as error:
            # Do not include response bodies: GitHub may echo sensitive request data.
            raise GitHubError(f"GitHub HTTP {error.code} for {method} {path}") from error
        except urllib.error.URLError as error:
            raise GitHubError(f"GitHub network error for {method} {path}: {error.reason}") from error